export const API_DOMAIN = process.env.REACT_APP_API_DOMAIN
export const BOILERPLATE_CANDIDATE_ID = process.env.REACT_APP_BOILERPLATE_CANDIDATE_ID
export const BOILERPLATE_USER_ID = process.env.REACT_APP_BOILERPLATE_USER_ID
export const BOILERPLATE_CANDIDATE_TOKEN = process.env.REACT_APP_BOILERPLATE_CANDIDATE_TOKEN
